import type { Book } from "./types";

export const books: Book[] = [
  {
    id: 1,
    img: "https://covers.openlibrary.org/b/id/8225261-L.jpg",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    rating: 4.8,
  },
  {
    id: 2,
    img: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    title: "1984",
    author: "George Orwell",
    rating: 4.7,
  },
  {
    id: 3,
    img: "https://covers.openlibrary.org/b/id/7352165-L.jpg",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    rating: 4.5,
  },
  {
    id: 4,
    img: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    rating: 4.6,
  },
  {
    id: 5,
    img: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    rating: 4.3,
  },
  {
    id: 6,
    img: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    rating: 4.8,
  },
  {
    id: 7,
    img: "https://covers.openlibrary.org/b/id/7222161-L.jpg",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    rating: 4.4,
  },
  {
    id: 8,
    img: "https://covers.openlibrary.org/b/id/8775116-L.jpg",
    title: "Brave New World",
    author: "Aldous Huxley",
    rating: 4.5,
  },
  {
    id: 9,
    img: "https://covers.openlibrary.org/b/id/7222241-L.jpg",
    title: "Moby-Dick",
    author: "Herman Melville",
    rating: 4.1,
  },
  {
    id: 10,
    img: "https://covers.openlibrary.org/b/id/8234140-L.jpg",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    rating: 4.9,
  },
  {
    id: 11,
    img: "https://covers.openlibrary.org/b/id/7884864-L.jpg",
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    rating: 4.6,
  },
  {
    id: 12,
    img: "https://covers.openlibrary.org/b/id/153541-L.jpg",
    title: "Animal Farm",
    author: "George Orwell",
    rating: 4.5,
  },
  {
    id: 13,
    img: "https://covers.openlibrary.org/b/id/8234176-L.jpg",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    rating: 4.3,
  },
  {
    id: 14,
    img: "https://covers.openlibrary.org/b/id/8090907-L.jpg",
    title: "The Alchemist",
    author: "Paulo Coelho",
    rating: 4.4,
  },
  {
    id: 15,
    img: "https://covers.openlibrary.org/b/id/8232381-L.jpg",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    rating: 4.7,
  },
  {
    id: 16,
    img: "https://covers.openlibrary.org/b/id/8774692-L.jpg",
    title: "The Book Thief",
    author: "Markus Zusak",
    rating: 4.6,
  },
  {
    id: 17,
    img: "https://covers.openlibrary.org/b/id/8319251-L.jpg",
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    rating: 4.8,
  },
  {
    id: 18,
    img: "https://covers.openlibrary.org/b/id/7222166-L.jpg",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    rating: 4.7,
  },
  {
    id: 19,
    img: "https://covers.openlibrary.org/b/id/8336421-L.jpg",
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    rating: 4.4,
  },
  {
    id: 20,
    img: "https://covers.openlibrary.org/b/id/8775006-L.jpg",
    title: "Les Misérables",
    author: "Victor Hugo",
    rating: 4.6,
  },
];
